# [Choice] Alpine version: 3.16, ..., 3.20
#ARG VARIANT="alpine-3.20"
ARG VARIANT="bookworm"
FROM mcr.microsoft.com/vscode/devcontainers/base:${VARIANT}

LABEL maintainer="Alex Thissen (athissen@killer-apps.nl)"
