# See here for image contents: https://github.com/microsoft/vscode-dev-containers/tree/v0.154.0/containers/alpine/.devcontainer/base.Dockerfile

# [Choice] Alpine version: 3.16, ..., 3.20
ARG VARIANT="alpine-3.20"

FROM mcr.microsoft.com/vscode/devcontainers/base:${VARIANT}
