name: "Prebuild devcontainer"
on:
  workflow_dispatch:
    # push:
    #   branches:
    #   - main
    # pull_request:
    #   paths:
    #     - src/templates/**
    #     - .github/workflows/prebuild.yaml
    #     - .github/actions/**
        
jobs:
  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        versions: ['2.15','2.16','2.17','2.18','2.19','latest']
    steps:
      - name: Checkout latest
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Prebuild images
        uses: devcontainers/ci@v0.3
        with:
          subFolder: src/images/cc65
          imageName: docker.io/atarilynx/cc65base
          imageTag: 1.0-${{matrix.versions}}
          push: always
          template: "${{ matrix.versions }}"
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}