name: "CI - Test Manual"
on:
  workflow_dispatch: 

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        templates: ['cc65']
    steps:
      - uses: actions/checkout@v3

      - name: Smoke test for '${{ matrix.templates }}'
        id: smoke_test
        uses: ./.github/actions/smoke-test
        with:
          template: "${{ matrix.templates }}"
